//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkDownload
    {
        public long Id { get; set; }
        public string NameFile { get; set; }
        public string NameFileUrl { get; set; }
        public string LinkGet { get; set; }
        public string LinkDownload1 { get; set; }
        public Nullable<int> NumberDown { get; set; }
        public string CreateDate { get; set; }
    }
}
