//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepComment
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string RepComments { get; set; }
        public string PostDate { get; set; }
        public Nullable<long> IdArticle { get; set; }
        public Nullable<int> Daduyet { get; set; }
        public Nullable<long> IdComment { get; set; }
        public string Website { get; set; }
        public string Images { get; set; }
        public Nullable<int> Show { get; set; }
        public Nullable<int> Spam { get; set; }
    
        public virtual Comment Comment { get; set; }
    }
}
