//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingSendEmail
    {
        public int Id { get; set; }
        public Nullable<int> Port { get; set; }
        public string Host { get; set; }
        public string EmailSend { get; set; }
        public string Password { get; set; }
        public string FooterBody { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> Server { get; set; }
    }
}
