//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsUser
    {
        public int Id { get; set; }
        public Nullable<int> QLArticle { get; set; }
        public Nullable<int> QLQuangCao { get; set; }
        public Nullable<int> QLComment { get; set; }
        public Nullable<int> QLBannerImage { get; set; }
        public Nullable<int> QLMenu { get; set; }
        public Nullable<int> QLPage { get; set; }
        public Nullable<int> QLUser { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EditArticleMe { get; set; }
        public Nullable<int> DelArticleMe { get; set; }
        public Nullable<int> NotDelArticle { get; set; }
        public Nullable<int> NotDelMenu { get; set; }
        public Nullable<int> NotDelPage { get; set; }
        public Nullable<int> NotDelUser { get; set; }
        public Nullable<int> EmailComment { get; set; }
        public Nullable<int> QLSettings { get; set; }
        public Nullable<int> QLNotification { get; set; }
        public Nullable<int> QLVideos { get; set; }
        public Nullable<int> QLSoftware { get; set; }
        public Nullable<int> QLLienHe { get; set; }
    
        public virtual User User { get; set; }
    }
}
