//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsComment
    {
        public int Id { get; set; }
        public Nullable<bool> HideShow { get; set; }
        public Nullable<int> NumberShow { get; set; }
        public Nullable<int> NumberShowRep { get; set; }
        public Nullable<int> AvatarStyle { get; set; }
        public Nullable<bool> SendEmailComment { get; set; }
        public Nullable<bool> SendEmailChoDuyet { get; set; }
        public Nullable<bool> Login { get; set; }
        public Nullable<bool> ActiveAllComment { get; set; }
        public string StringSpam { get; set; }
        public string EmailSpam { get; set; }
        public Nullable<bool> FacebookComment { get; set; }
        public Nullable<int> UserEmail { get; set; }
        public Nullable<int> ServerEmail { get; set; }
    }
}
