//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string Meta { get; set; }
        public string HTMLCode { get; set; }
        public string HTMLComment { get; set; }
        public string HTMLFanPage { get; set; }
        public Nullable<bool> FanPageFooter { get; set; }
        public Nullable<bool> FanPageRight { get; set; }
        public string StyleBannerImage { get; set; }
        public Nullable<int> NumberMaxTop { get; set; }
    }
}
