//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThongKeTruyCap
    {
        public int MaTB { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public long SoTruyCap { get; set; }
    }
}
